fastmeds/project/views.py
from flask import Blueprint, render_template, request, session, flash, redirect, session, url_for
from flask import redirect, url_for

from hashlib import sha256

from project.db import get_orders, check_for_user, add_user, user_already_exists

from project.db import get_categories, get_items_for_category, get_category, get_product, search_items, is_admin, add_category, add_product

from project.session import get_basket, add_to_basket, remove_from_basket, empty_basket, convert_basket_to_order, _save_basket_to_session, get_user
from project.forms import NewCheckoutForm, LoginForm, RegisterForm, orderCheckout, AddCategoryForm, AddProductForm
from project.models import Category, Item
from werkzeug.security import generate_password_hash, check_password_hash
from . import mysql

#groups all names under the namespace
bp = Blueprint('main', __name__)

#if homepages get visited
@bp.route('/')
def index():
    return render_template('index.html', categories = get_categories())

#products page for a specific category
@bp.route('/category/<int:categoryid>/')
def products(categoryid):
    products = get_items_for_category(categoryid)
    return render_template('products.html', products = products, category= get_category(categoryid))

#product details page for a specific product
@bp.route('/product/<int:product_id>/')
def product_details(product_id):
    product = get_product(product_id)
    return render_template('product_details.html', product=product)

# Order page, where users can see their basket and add products
@bp.route('/order/', methods=['POST', 'GET'])
def order():
    product_id = request.args.get('product_id')
    if 'order_id' not in session:
        session['order_id'] = 1  # arbitrary, for demo

    order = get_basket()  # This should return an object with an .items attribute (list of BasketItem)
    if product_id:
        print(f'user requested to add product id = {product_id}')
        # Add-to-basket logic would go here

    return render_template('order.html', order=order, totalprice=order.total_cost())

# Adding items to the basket
@bp.post('/basket/<int:product_id>/')
def adding_to_basket(product_id):
    try:
        quantity = int(request.form.get('quantity', 1))
        if quantity < 1:
            quantity = 1
    except ValueError:
        quantity = 1
    add_to_basket(product_id, quantity)
    return redirect(url_for('main.order'))

# # Adding items to the basket with a specified quantity
# @bp.post('/basket/<int:item_id>/<int:quantity>/')
# def adding_to_basket_with_quantity(item_id, quantity):
#     add_to_basket(item_id, quantity)
#     return redirect(url_for('main.order'))

# Clear the basket
@bp.post('/clearbasket/')
def clear_basket():
    empty_basket()
    flash('Basket cleared.')
    return redirect(url_for('main.order'))

# Remove an item from the basket
@bp.post('/removebasketitem/<string:item_id>/')
def remove_basketitem(item_id):
    basket = get_basket()
    item = basket.get_item(item_id)

    if item:
        flash(f"Removed '{item.product.name}' from basket.")
        remove_from_basket(item_id)
    else:
        flash("Item not found in basket.", "warning")

    return redirect(url_for('main.order'))

# Checkout page where users can enter their details
@bp.route('/checkout/', methods=['POST', 'GET'])
def checkout():
    if 'user' not in session:
        flash('Please log in to proceed to checkout.', 'error')
        return redirect(url_for('main.login'))

    form = NewCheckoutForm()
    basket = get_basket()
    user = session['user']  # Use the session directly

    if request.method == 'GET' and user:
        form.firstname.data = user.get('firstname', '')
        form.surname.data = user.get('surname', '')
        form.email.data = user.get('email', '')
        form.phone.data = user.get('phone', '')
        form.address.data = user.get('address', '')
        form.city.data = user.get('city', '')
        form.postcode.data = user.get('postcode', '')
        form.state.data = user.get('state', '')
        print("FORM DATA:", form.data)

    if request.method == 'POST':
        print("POSTED DATA:", request.form)

    if form.validate_on_submit():
        session['order_info'] = {
            'firstname': form.firstname.data,
            'surname': form.surname.data,
            'email': form.email.data,
            'phone': form.phone.data,
            'address': form.address.data,
            'city': form.city.data,
            'postcode': form.postcode.data,
            'state': form.state.data,
            'payment': form.payment.data
        }
        flash('Thank you for your information, please confirm your order.')
        return redirect(url_for('main.order_summary'))
    elif request.method == 'POST':
        print("FORM ERRORS:", form.errors)
        flash('The provided information is missing or incorrect', 'error')

    return render_template('checkout.html', form=form, basket=basket)

# Success page after order confirmation
@bp.route('/success/')
def success():
    return render_template('success.html')

# Order summary page where users can review their order before finalizing
@bp.route('/order/summary', methods=['GET', 'POST'])
def order_summary():
    user_id = get_user()
    form = orderCheckout() 
    basket = get_basket()
    order_info = session.get('order_info')
    if not order_info:
        flash('Please fill in your details first.', 'error')
        return redirect(url_for('main.checkout'))

    if request.method == 'POST':
        # Insert order into database
        cur = mysql.connection.cursor()
        cur.execute("""
            INSERT INTO orders (userID, order_status, order_delivery_type, total_cost, userFirstName, userLastName, userEmail, userPhoneNumber)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """, (basket.userID, 'Confirmed', form.delivery.data, basket.total_cost(), order_info['firstname'], order_info['surname'], order_info['email'], order_info['phone']))
        order_id = cur.lastrowid


        # Insert items into order_items
        for item in basket.items:
            cur.execute("""
                INSERT INTO order_items (orderID, itemID, quantity)
                VALUES (%s, %s, %s)
            """, (order_id, item.product.id, item.quantity))
        mysql.connection.commit()
        cur.close()

        empty_basket()
        session.pop('order_info', None)
        flash('Order placed successfully!', 'success')
        return redirect(url_for('main.success'))
        

    return render_template('orderSummary.html', basket=basket, order_info=order_info, form = form, totalprice = basket.total_cost())

# Register a new user and add it to the database
@bp.route('/register/', methods = ['POST', 'GET'])
def register():
    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # Hash the password
            form.password.data = sha256(form.password.data.encode()).hexdigest()
            user = check_for_user(form.username.data, form.password.data)

            # if user_already_exists(form.username.data, form.email.data):
            if user:
                flash('User NAME or EMAIL already exists. Please choose a different user name or email.', 'error')
                return redirect(url_for('main.register'))

            # Add user to the database
            if add_user(form):
                flash('Registration successful! You can now log in.', 'success')
                return redirect(url_for('main.login'))
            else:
                flash('Registration failed. Please try again.', 'error')
                return redirect(url_for('main.register'))
    return render_template('register.html', form=form)

# Login page for users to access their accounts
@bp.route('/login/', methods = ['POST', 'GET'])
def login():
    form = LoginForm()
    if request.method == 'POST':

        if form.validate_on_submit():
            form.password.data = sha256(form.password.data.encode()).hexdigest()
            # Check if the user exists in the database
            user = check_for_user(
                form.username.data, form.password.data
            )
            if not user:
                flash('Invalid username or password', 'error')
                return redirect(url_for('main.login'))

            session['user'] = {
                            'user_id': user.info.id,
                            'firstname': user.info.firstname,
                            'surname': user.info.surname,
                            'email': user.info.email,
                            'phone': user.info.phone,
                            'address': user.info.address,
                            'city': user.info.city,
                            'postcode': user.info.postcode,
                            'is_admin': is_admin(user.info.id),
            }
            session['username'] = user.username
            #session['userpassword']=user.userpassword

            session['logged_in'] = True
            flash('Login successful!')
            return redirect(url_for('main.index'))

    return render_template('login.html', form = form)

# Logout route to clear the session and redirect to the homepage
@bp.route('/logout/')
def logout():
    session.clear()
    session.pop('username', None)
    session.pop('logged_in', None)
    flash('You have been logged out.')
    return redirect(url_for('main.index'))

# Manage orders and products, only accessible to admins
@bp.route('/manage/')
# @only_admins
def manage():
    # check if the user is logged in and is an admin
    if 'user' not in session or session['user']['user_id'] == 0:
        flash('Please log in before managing orders.', 'error')

fastmeds/project/templates/base.html
<!--written by Steven Baist-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fast Meds</title>
    <meta name="description" content="Fast Meds">

    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css"  href="{{ url_for('static', filename='css/style.css') }}">
    <!--place for css styles etc.-->

</head>

<body>
    <header>
            <nav class="navbar navbar-expand-lg brand_color_set mb-20">
              <div class="container-fluid">
                <a class="brand brand_color_set fw-bold fs-5" href="/" role="button"> <i class="bi bi-capsule-pill ms-1"></i> Fast Meds</a>
                <!-- 404 Test and 500 Error handling buttons -->
                <a class="btn btn-outline-danger ms-2" href="/main.404" role="button">404 Test</a>

                <a class="btn btn-outline-warning ms-2" href="/main.500" role="button">500 Test</a>  

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <div class="mx-auto d-flex">
                      <!--Search bar-->
                      <form class="d-flex" action="{{ url_for('main.search') }}" method="get">
                          <input class="form-control me-2" type="search" name="q" placeholder="Search..." aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                      </form>
                  </div>
                  <!--Basket button which redirects to basket.html website-->
                    {% if session['user'] and session['user']['is_admin'] %}
                    <a id="basket" class="btn" href="{{ url_for('main.manage') }} " role="button" style="margin-right: 5px;">ADMIN</a>
                    {% endif %}
                    {% if session['user'] %}
                    <a  id="logout" class="btn btn-outline-light" href="{{ url_for('main.logout') }}" role="button" style="margin-right: 5px;">Logout</a>
                    {% else %}
                    <a id="login" class="btn btn-outline-light" href="{{ url_for('main.login') }}" role="button" style="margin-right: 5px;">Login</a>
                    {% endif %}
                  <a id="basket" class="btn" href="{{ url_for('main.order') }}" role="button"><i class="bi bi-cart3" style="margin-right: 5px;"></i>Basket</a>
                </div>
              </div>
            </nav>
          

        {% with messages = get_flashed_messages(category_filter='message') %}
        {% if messages %}
            <div class="alert alert-primary text-center p-2" role="alert"
                style="margin: 0"
            >
            {% for message in messages %}
                {{ message }}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 
        {% with messages = get_flashed_messages(category_filter='error') %}
        {% if messages %}
            <div class="alert alert-danger text-center p-2" role="alert"
                style="margin: 0;"
            >
            {% for message in messages %}
                {{ message }}
            {% endfor %}
            </div>
        {% endif %}
        {% endwith %} 

        {% block head %}
        {% endblock %}
    </header>

    <!-- Main content -->
    <div class="container-md mt-5 mb-5" style="max-width: 1200px;">
        <main>
            {% block main %}
            {% endblock %}
        </main>
    </div>

     <!--Footer class, identical on every webpage and responsive-->
     <footer class="brand_color_set py-2">
        <div class="container">
          <div class="row">
            <div class="col-md-3">
              <h1>Fast Meds <i class="bi bi-capsule-pill"></i></h1>
              <p>Australia's #1 Choice for Medicine</p>
            </div>
            <div class="col-md-3">
              <h5>Customer Service</h5>
              <p>+61 490133742069</p>
            </div>
            <div class="col-md-3">
              <h5>Contact us @</h5>
              <p>help@fastmeds.com</p>
              <a href="https://www.instagram.com/ms.zulya" target="_blank" rel="noopener noreferrer">
                    <i class="bi bi-instagram"></i> Instagram
                </a>
            </div>
            <div class="col-md-3">
              <h5>Career</h5>
              <p>jobs@fastmeds.com</p>
            </div>
          </div>
        </div>
        <div class="d-flex justify-content-center mt-3">
          <p>&copy; 2025 Fast Meds. All rights reserved</p>
        </div>
      </footer>

<!-- Bootstrap 5 JS Bundle -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js">
</script>
</body>
</html>

fastmeds/project/templates/checkout.html
{% extends 'base.html' %}

{% import 'bootstrap5/form.html' as wtf %}

{% block main %}
<section class="mb-5 mt-5">
    <div class="container text-center">
        <div class="row">
            <div class="col-12">
                <h1>Checkout</h1>
                <p>
                    <strong>Thank you for your interest. 
                    Please complete the form below to proceed with your order.</strong>
                </p>
            </div>
        </div>
        <div class="row mt-4 justify-content-center p-3">
            <div class="col-md-6">
            <form method="POST">
                {{ wtf.render_form(form) }}
           </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

fastmeds/project/templates/login.html
{% extends 'base.html' %}

{% import 'bootstrap5/form.html' as wtf %}

{% block main %}
<section class="mb-5 mt-5">
    <div class="container text-center">
        <div class="row">
            <div class="col-12">
                <h1>User Login</h1>
                <p>
                    Please provide
                    your login details to access your account. 
                    If you do not have an account, please 
                    <a href="{{ url_for('main.register') }}">
                    register first
                    </a>    
                    .
                </p>
            </div>
        </div>
        <div class="row mt-4 justify-content-center p-3">
            <div class="col-md-6">
                {{ wtf.render_form(form) }}
            </div>
        </div>
    </div>
</section>
{% endblock %}

fastmeds/project/templates/order.html
{% extends 'base.html' %}

{% block main %}
<section class="mb-5">  
    <div class="container mt-5" style="max-width: 1200px;">
        <div class="row mt-2 mb-5">
            <div class="col-12">
                <h3 class="display-5 text-center">Shopping Basket</h3>
            </div>
        </div>

        {% for basket_item in order.items %}
        <div class="row mb-3">
            <div class="col-sm-12">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <div class="row">
                            <h5 class="lead col-md-8 col-sm-12">
                                {{ basket_item.product.name }}
                            </h5>
                            <p class="text-success float-end col text-end">
                                Price: {{ "$%.2f"|format(basket_item.product.price) }}
                            </p>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col" >
                                <img class="img-thumbnail"
                                     src="{{ url_for('static', filename='img/' + basket_item.product.name.split(' ')[0] +'.jpg') }}"
                                     style="max-height: 200px; min-height: 100px;"
                                >
                            </div>
                            <div class="col-8">
                                <p class="card-text">{{ basket_item.product.description }}</p>
                            </div>
                        </div>
                        <!-- Quantity controls -->
                        <div class="row">
                        <div class="col-12 text-center">
                            <div class="fw-bold mb-1">Quantity</div>
                            <div class="d-inline-flex align-items-center mb-3 justify-content-center">
                                <form method="POST" action="{{ url_for('main.update_quantity', item_id=basket_item.id, action='decrease') }}" style="display:inline;">
                                    <button type="submit" class="btn btn-secondary btn-sm">-</button>
                                </form>
                                <span class="mx-2">{{ basket_item.quantity }}</span>
                                <form method="POST" action="{{ url_for('main.update_quantity', item_id=basket_item.id, action='increase') }}" style="display:inline;">
                                    <button type="submit" class="btn btn-secondary btn-sm">+</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="float-end">
                            <form method="POST" action="{{ url_for('main.remove_basketitem', item_id=basket_item.id) }}">
                                <button type="submit" class="btn btn-link p-0 m-0" style="border: none; background: none;" title="Remove item">
                                    <svg xmlns="http://www.w3.org/2000/svg" color="rgb(227, 56, 56)" width="24" height="24" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                                    </svg>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
 
       <div class="row mt-4 mb-1 justify-content-between">
               <!-- total price and controls -->
        <div class="lead-5 text-center mb-3">
            TOTAL: {{ "$ %.2f"|format(totalprice) }}
        </div>
            {% if order.items|length > 0 %}
                <div class="col-2">
                    <form method="POST" action="{{ url_for('main.clear_basket') }}">
                        <input type="submit" value="Clear" class="btn btn-danger mb-3">
                    </form>
                </div>
                <div class="col-2 d-flex justify-content-end">
                    <a href="{{ url_for('main.checkout') }}" class="btn btn-success mb-3">Checkout</a>
                </div>
            {% endif %}
        </div>
        {% if order.items|length == 0 %}
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <a href="{{ url_for('main.index') }}" class="btn btn-primary mb-3">Continue to shop</a>
            </div>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

fastmeds/project/templates/product_details.html
{% extends 'base.html' %}

{% import 'bootstrap5/form.html' as wtf %}

{% block main %}
      <!--Card for the datailed product-->
        <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
                <!--Carousel for 2 pictures of the item-->
                <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ url_for('static', filename='img/' + product.name.split(' ')[0] +'.jpg') }}" class="card-img-top" alt="card-img-top">
                    </div>
                    <div class="carousel-item">
                        <img src="{{ url_for('static', filename='img/' + product.name.split(' ')[0] +'.jpg') }}" class="card-img-top" alt="card-img-top">
                    </div>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
              </div>
              <!--Item details, including manufacturer, price, desription and id-->
              <div class="col-md-8">
                <div class="card-body h-100 d-flex flex-column justify-content-between">
                  <div style="margin-bottom: 20px">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description}}</p>
                    <div class="mb-2">
                      <span class="badge bg-success in-stock-badge">IN STOCK</span>
                    </div>
                    <p class="card-text"><small class="text-muted">Price: $ {{ product.price}}</small></p>
                  </div>
                  <!-- Place form at the bottom right -->
                  <div class="d-flex justify-content-between  mt-auto">
                    <form method="POST"
                          action="{{ url_for('main.adding_to_basket', product_id=product.id) }}"
                          class="d-flex justify-content-between w-100"
                          style="width: 220px;">
                      <div class="input-group mb-1 me-3" style="width: 110px;">
                        <span class="input-group-text p-1" style="font-size: 1rem; border-radius: 0.375rem 0 0 0.375rem;">Qty</span>
                        <input
                          type="number"
                          name="quantity"
                          value="1"
                          min="1"

                          style="width: 55px; font-size: 1.1rem; border-radius: 0 0.375rem 0.375rem 0; border: 1px solid #ced4da;"
                          aria-label="Quantity"
                        >
                      </div>
                      <input
                        type="submit"
                        value="+ Add to Basket"
                        class="btn add_button brand_color_set w-100"
                        style="height: 48px; font-size: 1.25rem; font-weight: bold;"
                      >
                    </form>
                  </div>
                </div>
              </div>  
            </div>
          </div>
{% endblock %}

fastmeds/project/templates/products.html
{% extends 'base.html' %}

{% block head %}
<!-- add a big banner to welcome user -->
<div class="p-5 text-white bg-image"
    style="background-image: url({{url_for('static', filename='img/pexels-etatics-inc-252430999-12512669.jpg')}}); background-size: cover;">
    <div class="text-white text-center py-5 px-4">
        <div>
            <h1 class="display-2">Products choices for {{ category.name }}</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block main %}
<!-- display items for the specific category -->
<section class="mb-5">

    <div class="text-dark text-center">
        <div>
            <p class="h3 text-dark mb-4">Select a product from below</p>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3 justify-content-center" style="margin:10px;">
                        {% for product in products %}
                            <div class="col prod_card"><div class="card">
                                    <a href="{{ url_for('main.product_details', product_id=product.id) }}">
                                        <img src="{{ url_for('static', filename='img/' + product.name.split(' ')[0] +'.jpg') }}" class="card-img-top" alt="card-img-top">
                                    </a>
                                    <div class="card-body d-grid gap-2">
                                        <div class="mb-2">
                                            <span class="badge bg-success in-stock-badge">IN STOCK</span>
                                        </div>
                                        <h5 class="card-title">{{ product.name }}</h5>
                                        <h2>$ {{ product.price }}</h2>
                                    </div>
                                    <div class="card-footer">
                                    <form method="POST"
                                        action="{{ url_for('main.adding_to_basket', product_id=product.id) }}"
                                        class="d-flex flex-column align-items-center w-100">
                                        <div class="input-group mb-2" style="width: 70px;">
                                            <span class="input-group-text p-1" style="font-size: 0.9rem; border-radius: 0.375rem 0 0 0.375rem;">Qty</span>
                                            <input
                                                type="number"
                                                name="quantity"
                                                value="1"
                                                min="1"
                                                class="form-control text-center p-1"
                                                style="width: 35px; font-size: 1rem; border-radius: 0 0.375rem 0.375rem 0;"
                                                aria-label="Quantity"
                                            >
                                        </div>
                                        <input
                                            type="submit"
                                            value="+ Add to Basket"
                                            class="btn add_button brand_color_set w-100"
                                            style="font-weight: bold; letter-spacing: 0.5px;"
                                        >
                                    </form>
                                </div>

                                </div>
                            </div>
                        {% endfor %}
        </div>
    </div>

    <div class="row ps-5 ps-5">
        <!--margin under card-->
    </div>

</section>
{% endblock %}

fastmeds/project/templates/search.html
{% extends 'base.html' %}

{% block main %}

    <div class="container text-center">
        <h1>Results for "{{ query }}"</h1>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3 justify-content-center" style="margin:10px;">
        {% for item in results %}
        <div class="col prod_card"><div class="card">
            <a href="{{ url_for('main.product_details', product_id=item.id) }}">
                <img src="{{ url_for('static', filename='img/' + item.name.split(' ')[0] +'.jpg') }}" class="card-img-top" alt="card-img-top">
            </a>
            <div class="card-body d-grid gap-2">
                <h5 class="card-title">{{ item.name }}</h5>
                <h2>$ {{ item.price }}</h2>
            </div>
            <div class="card-footer">
            <form method="POST"
                action="{{ url_for('main.adding_to_basket', product_id=item.id) }}"
                class="d-flex flex-column align-items-center w-100">
                <div class="input-group mb-2" style="width: 70px;">
                    <span class="input-group-text p-1" style="font-size: 0.9rem; border-radius: 0.375rem 0 0 0.375rem;">Qty</span>
                    <input
                        type="number"
                        name="quantity"
                        value="1"
                        min="1"
                        class="form-control text-center p-1"
                        style="width: 35px; font-size: 1rem; border-radius: 0 0.375rem 0.375rem 0;"
                        aria-label="Quantity"
                    >
                </div>
                <input
                    type="submit"
                    value="+ Add to Basket"
                    class="btn add_button brand_color_set w-100"
                >
            </form>
        </div>

        </div>
        </div>
        {% endfor %}
    </div>
    </div>

{% endblock %}